name: frutas_verduras_luisitos
description: "Aplicación Flutter para tienda de frutas y verduras"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  geocoding: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
